"""Render mag-usb's config.toml from mag-recorder's [mag] section.

mag-usb (the C subprocess) reads its own TOML schema — see the
upstream `tools/config.toml` and `docs/Configuration.md`.  Rather
than ask the operator to maintain a second config file under
`/etc/mag-usb/`, mag-recorder owns the operator-facing settings in
`/etc/mag-recorder/mag-recorder-config.toml` and materializes a
private mag-usb-shaped TOML at daemon startup that the C binary
loads via its ``-f`` flag (added in wittend/mag-usb
``sigmond-integration`` PR #2).

The rendered file is a transient runtime artifact, **not**
operator-facing.  Operators edit `mag-recorder-config.toml` and run
``systemctl restart mag-recorder``; this file is regenerated at
every daemon start from the live ``[mag]`` section.

Defaults below match wittend/mag-usb's ``tools/config.toml`` so a
fresh deploy works without the mag-usb repo being checked out at
``/opt/git/sigmond/mag-usb``.  CONTRACT v0.6 §16.7 says clients
should not duplicate upstream-binary config, but in this case the
operator-facing surface (mag-recorder-config.toml) is the single
source of truth and the driver TOML is derived — duplication only
exists internally for sane defaults when mag-recorder-config.toml
omits a key.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any


# Defaults pulled from wittend/mag-usb tools/config.toml, sigmond-integration
# branch.  cc / nos / tmrc / drdy match upstream's shipped values and
# are now actually programmed on-chip (see mag-usb PR #1).
_DRIVER_DEFAULTS: dict[str, Any] = {
    "cycle_count":          400,
    "nos":                  60,
    "tmrc_rate":            0x96,
    "drdy_delay_ms":        10,
    "sampling_mode":        "POLL",
    "remote_temp_address":  0x1F,
    "orientation":          {"x": 0, "y": 0, "z": 0},
}


def render(mag_recorder_config: dict, dest: Path | str) -> Path:
    """Materialize a mag-usb-shaped TOML from a loaded mag-recorder config.

    Reads the ``[mag]`` section (with the defaults above filling in
    anything the operator didn't override) and writes a complete
    mag-usb config TOML to ``dest`` atomically (``.part`` + rename).

    Returns the destination ``Path`` so callers can pass it to
    ``mag-usb -f``.
    """
    mag = mag_recorder_config.get("mag", {}) or {}

    port      = mag.get("device", "/dev/ttyMAG0")
    addr      = int(mag.get("i2c_address", 0x23))
    cc        = int(mag.get("cycle_count",   _DRIVER_DEFAULTS["cycle_count"]))
    nos       = int(mag.get("nos",            _DRIVER_DEFAULTS["nos"]))
    tmrc      = int(mag.get("tmrc_rate",      _DRIVER_DEFAULTS["tmrc_rate"]))
    drdy      = int(mag.get("drdy_delay_ms",  _DRIVER_DEFAULTS["drdy_delay_ms"]))
    mode      = str(mag.get("sampling_mode",  _DRIVER_DEFAULTS["sampling_mode"]))
    temp_addr = int(mag.get("remote_temp_address", _DRIVER_DEFAULTS["remote_temp_address"]))
    ori       = mag.get("orientation",        _DRIVER_DEFAULTS["orientation"]) or {}

    # Cycle count and address ranges per RM3100 datasheet / mag-usb -c
    # guard (cmdmgr.c rejects cc>0x320 and cc<=0).
    if not (0 < cc <= 0x320):
        raise ValueError(
            f"mag.cycle_count={cc} is out of range (1..800); "
            f"RM3100 rejects values <=0 or > 0x320"
        )
    if not (0 < addr <= 0x7F):
        raise ValueError(
            f"mag.i2c_address=0x{addr:02X} is out of range (0x01..0x7F)"
        )
    if mode not in ("POLL", "CMM"):
        raise ValueError(f"mag.sampling_mode={mode!r} must be 'POLL' or 'CMM'")

    text = (
        "# mag-usb driver config -- AUTO-GENERATED by mag-recorder.\n"
        "# DO NOT EDIT BY HAND.  Edit /etc/mag-recorder/mag-recorder-config.toml\n"
        "# instead; this file is regenerated on every mag-recorder restart from\n"
        "# the [mag] section of that config.\n"
        "\n"
        "[i2c]\n"
        "use_I2C_converter = true\n"
        f'portpath          = "{port}"\n'
        "scan_bus          = false\n"
        "\n"
        "[magnetometer]\n"
        f"address           = 0x{addr:02X}\n"
        f"cc_x              = {cc}\n"
        f"cc_y              = {cc}\n"
        f"cc_z              = {cc}\n"
        f"tmrc_rate         = 0x{tmrc:02X}\n"
        f"nos_reg_value     = {nos}\n"
        f"drdy_delay        = {drdy}\n"
        f'sampling_mode     = "{mode}"\n'
        "\n"
        "[mag_orientation]\n"
        f"mag_translate_x   = {int(ori.get('x', 0))}\n"
        f"mag_translate_y   = {int(ori.get('y', 0))}\n"
        f"mag_translate_z   = {int(ori.get('z', 0))}\n"
        "\n"
        "[temperature]\n"
        f"remote_temp_address = 0x{temp_addr:02X}\n"
    )

    dest_path = Path(dest)
    dest_path.parent.mkdir(parents=True, exist_ok=True)
    tmp = dest_path.with_suffix(dest_path.suffix + ".part")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(dest_path)
    return dest_path
